version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Ensure it can build
          command: go build
      - run:
          name: Ensure it pass test
          command: go test
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
